Las matemáticas son un área de conocimiento muy extenso, por lo que hablar de todas las herramientas disponibles ¡nos podría llevar años! En este curso nos vamos a enfocar en un tipo general de modelo y de sistema ecológico: aquellos que cambian rápidamente con el tiempo, también llamados dinámicos.

Las herramientas matemáticas más comunmente utilizadas para estudiar estos sistemas son las ecuaciones diferenciales ordinarias, ecuaciones por diferencias finitas y el álgebra de matrices. Las ecuaciones diferenciales y por diferencias finitas son muy parecidas entre sí, porque nos representar y medir los cambios que sufre un sistema ecológico a través del tiempo en cada uno de sus componentes. Además es fácil representar las ideas plasmadas diagramáticamente en ellas. El álgebra de matrices, por otro lado, nos sirve para *conectar* los cambios de los diferentes componentes del sistema de estudio, y así hacer cálculos sobre sus cambios *como un todo*. Por supuesto que para poder utilizar las matrices de este modo, tenemos que echar mano de una serie de supuestos de *linealidad*, de modo que el álgebra lineal también es una herramienta básica.

Como podemos ver, gran parte de este curso estará enfocado en *entender y medir los cambios*. Te preguntarás entonces ¿cambios de qué? En ecología, estos son algunos de los cambios que nos interesa observar:

1. Número de individuos de una especie
2. Cantidad de materia orgánica almacenada en la vegetación
3. Calorías consumidas por una población de aves
4. Probabilidad de extinción de una especie

Cuando medimos cambios entonces, es necesario observar el estado del mundo natural en diferentes puntos a lo largo del tiempo. Por lo tanto, la modelación matemática también requiere desarrollar buenas habilidades estadísticas. Estas últimas nos permitirán entender probabilísticamente a los sistemas ecológicos a partir de los mecanismos que representamos en los modelos matemáticos. Más adelante veremos a qué nos referimos con *probabilísticamente*.

### Relación entre las herramientas matemáticas y los sistemas ecológicos

Los sistemas ecológicos son muy variados, de modo que las herramientas matemáticas disponibles o que conocemos no siempre reflejan ciertos aspectos importantes de los sistemas ecológicos. Un ejemplo notable de ello es la variación de atributos entre individuos de una población. Supongamos que estamos modelando el crecimiento de una población, y la tasa neta de crecimiento depende de la cantidad de adultos reproductores y del crecimiento exponencial de los gametos fértiles en cada adulto reproductor, lo cual ocurre en corales y algunas plantas. 

El crecimiento poblacional como tal, puede modelarse con ecuaciones diferenciales ordinarias, mientras que el crecimiento de los gametos fértiles dentro de cada adulto requiere de  otras herramientas mucho más avanzadas.