La clasificación de los modelos depende de la herramienta que se utiliza para desarrollarlos. En la sección "Cómo construir un modelo", mencioné brevemente que uno de los pasos es la formulación de un modelo "conceptual", en forma de un esquema o diagrama. Esta clasificación la podemos ampliar un poco:

1. **Modelo conceptual o verbal**. Descripciones en lenguaje natural.
2. **Diagramático**. Representación gráfica (diagramas de flujo o cajas).
3. **Físico**. Representación a escala de sistema (sistemas hidráulicos).
4. **Formal**. Matemático (algebráico o sistemas de ecuaciones).

Aquí nos centraremos en ver a mayor profundidad los modelos formales, en clasificar los modelos matemáticos. @haefner1998modeling sugiere la siguiente clave dicotómica de clasificación:

1. **¿Las matemáticas representan de manera explícita el proceso de interés?**

    1.1. **Sí**: Modelo mecanístico
    
    1.2. **No**: Modelo descriptivo, fenomenológico
    
2. **¿Las matemáticas representan de manera explícita las condiciones del estado futuro del sistema?**

    2.1. **Sí**: Modelo dinámico
    
    2.2. **No**: Modelo estático
    
3. **¿Las matemáticas representan el tiempo de manera contínua?**

    3.1. **Sí**: Modelo conínuo
    
    3.2. **No**: Modelo discreto (el tiempo sólo toma valores enteros, un día, un año)

4. **¿Las matemáticas representan explícitamente el espacio?**

    4.1. **Sí**: Modelo espacialmente heterogéneo
    
    4.2. **No**: Modelo espacialmente homogéneo
    
5. **¿Las matemáticas permiten la ocurrencia de eventos aleatorios?**

    5.1. **Sí**: Modelo estocástico
    
    5.2. **No**: Modelo determinístico

### Ejemplos

#### Modelo de presa-depredador de El modelo de Lotka-Volterra [-@volterra1928variations]

Este modelo representa cómo cambia el número de liebres y linces a través del tiempo con un sistema de ecuaciones diferenciales. El cambio en los números de individuos depdende de

1. Crecimiento poblacional del depredador en relación a las presas disponibles para que el depredador se alimente
2. Crecimiento poblacional innato de las presas
3. Mortalidad de presas en relación a la cantidad de depredadores
4. Mortalidad innata del depredador

El modelo entonces representa el mecanismo del sistema, por lo que es un modelo **mecanístico**. Debido a que representa el cambio del número de individuos en el tiempo, es un modelo **dinámico**. Por el momento no contamos con información suficiente para decir si es contínuo o discreto, pero no hay mención del componente espacial, por lo que podemos suponer que se trata de un modelo **espacialmente homogéneo**. La solución al modelo clásico de la figura \@ref(fig:volterra), muestra un patrón regular, lo cual se debe a que todos los parámetros son constantes, y por lo tanto es un modelo **determinista**.

#### Modelo del panal de abejas

@wilensksi2003honey desarrolló un modelo para representar cómo las abejas construyen un panal, por medio de una serie de reglas que rigen el comportamiento de abejas individuales. Debido a que el mecanismo está representado en el comportamiento colectivo de las abejas, es un modelo **mecanístico**. El modelo también muestra la progresión de la construcción del panal, por lo que es un modelo **dinámico**, y debido a que cualquiera de los eventos posibles pueden ocurrir en cualquier momento es en tiempo **contínuo**. También representa la estructura del panal en unidades espaciales, por lo que es **espacialmente heterogéneo**. Finalmente, los eventos que ocurren son aleatorios, o sea que el resultado de  una realización del modelo será diferente de otra, por lo que es un modelo **estocástico**. Te invito a explorar este modelo por medio de la aplicación en línea de [NetLogo](https://www.netlogoweb.org/launch#https://www.netlogoweb.org/assets/modelslib/Sample%20Models/Biology/Honeycomb.nlogo).

A continuación veremos a mayor profundidad los modelos deterministicos y estocásticos.

### Modelos determinisicos


      
### Modelos estocásticos